### ISSUE TITLE
SyntaxError: f-string: expecting '}' on line 399

### ISSUE THREAD

**Issue by mikejamescalvert** [siropkin/robinhood-ai-trading-bot#27]
Getting this issue after last update:

File "E:\_Trading\RobinhoodAI\main.py", line 399
    log_info(f"Portfolio stocks to proceed: {"None" if len(portfolio) == 0 else ', '.join(portfolio)}")
                                              ^^^^
SyntaxError: f-string: expecting '}'

**Comment by siropkin** [comment]
Ooookey, for some reason i do not have those errors on my PC and I work "in the dark" so thank you for your patient and feedback!
I hope I fixed it in v2.6.0.
In that version I also added SQL Lite DB that store trading logs and helps to prevent PDT #17 issue.

**Comment by mikejamescalvert** [comment]
No problem at all!  Happy to work on this with you, I am very interested in where this is going :)

**Comment by mikejamescalvert** [comment]
Tested and verified
