### ISSUE TITLE
 Error making AI-based decision: name 'PDT_PROTECTION' is not defined

### ISSUE THREAD

**Issue by mikejamescalvert** [siropkin/robinhood-ai-trading-bot#34]
Looks like PDT_PROTECTION is not defined anywhere, is this suppose to be a config?

**Comment by siropkin** [comment]
Maybe it's because i introduced that param after you created your local `config.py` file.
Try do add this at the end of your local `config.py` file:
```
PDT_PROTECTION = False                       # Pattern day trader protection (False - disable protection). See: https://robinhood.com/us/en/support/articles/pattern-day-trade-protection/
```

**Comment by mikejamescalvert** [comment]
Added this and it worked, thanks!
